server:
  port: 9999
  servlet:
    context-path: /my-app/api

spring:
  application:
    name: my-app

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  #开启后 如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
  page-size-zero: true
  #分页合理性配置
  #如果 pageNum <= 0 会查询第一页，如果 pageNum > pages 会查询最后一页。
  reasonable: true